spring:
  application:
    name: ambition-backend

  data:
    mongodb:
      uri: mongodb+srv://AmbitionAdmin:Ambition03@cluster0.apd1rnr.mongodb.net/?appName=Cluster0

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: sanchigangurde3@gmail.com
    password: wpln cbhp gzfd fqqo
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
